FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

WORKDIR /App
COPY ./LogCommunication/LoggingCommunicationLibrary ./LogCommunication/LoggingCommunicationLibrary
COPY ./Shop/Shop.Catalog.Api ./Shop/Shop.Catalog.Api

WORKDIR /App/Shop/Shop.Catalog.Api
RUN dotnet restore
RUN dotnet publish -c Release -o ../../out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "Shop.Catalog.Api.dll"]