version: '1.0'

services: 
  sql-server: 
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Str#ng_Passw#rd"
    ports: 
      - 1433:1433
    networks: 
      - shop-env

  snowflake-factory:
    image: snowflake-factory
    ports: 
      - 8081:80
    networks: 
      - shop-env  
    expose: 
      - "80"

  shop-app:
    image: shop
    ports: 
      - 8082:80
    networks: 
      - shop-env
    depends_on:
      - snowflake-factory
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks: 
  shop-env: