version: '1.0'

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports: 
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic

  log-service:
    image: log-service
    ports: 
      - 8084:80
    networks:
      - elastic
      - kibana
    depends_on: 
      - elasticsearch
      - kibana

  sql-server: 
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Str#ng_Passw#rd"
    ports: 
      - 1433:1433
    networks: 
      - shop-env

  snowflake-factory:
    image: snowflake-factory
    ports: 
      - 8081:80
    networks: 
      - snowflake-id  
    expose: 
      - "80"

  shop-catalog-proxy:
    image: shop-catalog-proxy
    build:
      context: .
    ports:
      - "20000:80"
    depends_on:
      - shop-catalog-api01
      - shop-catalog-api02
    networks:
      - shop-catalog-network

  shop-catalog-api01:
    image: shop-catalog-api
    ports: 
      - 8082:80
    networks:
      - shop-catalog-network
      - shop-env  
      - snowflake-id
      - kibana
    depends_on:
      - sql-server
      - snowflake-factory
    environment:
      - "SqlServerCredentials:Server=sql-server"
      - "SqlServerCredentials:Port=1433"
      - "SqlServerCredentials:Schema=ShopDb"
      - "SqlServerCredentials:User=sa"
      - "SqlServerCredentials:Password=Str#ng_Passw#rd"

  shop-catalog-api02:
    image: shop-catalog-api
    ports: 
      - 8083:80
    networks: 
      - shop-catalog-network
      - shop-env  
      - snowflake-id
      - kibana
    depends_on:
      - sql-server
      - snowflake-factory
    environment:
      - "SqlServerCredentials:Server=sql-server"
      - "SqlServerCredentials:Port=1433"
      - "SqlServerCredentials:Schema=ShopDb"
      - "SqlServerCredentials:User=sa"
      - "SqlServerCredentials:Password=Str#ng_Passw#rd"

  shop-frontend:
    image: shop-frontend
    ports: 
      - 8085:80
    networks: 
      - kibana
      - shop-env
      - shop-catalog-network
    depends_on:
      - shop-catalog-proxy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  shop-env:
  snowflake-id:
  kibana:
    driver: bridge
  elastic:
    driver: bridge
  shop-catalog-network:
      driver: bridge
