version: '1.0'

services: 
  snowflake-factory:
    image: snowflake-factory
    ports: 
      - 8081:80
    networks: 
      - shop-env  
    expose: 
      - "80"

  shop-app:
    image: shop
    ports: 
      - 8082:80
    networks: 
      - shop-env
    depends_on:
      - snowflake-factory

networks: 
  shop-env: